fix: Enforce operator string length (#288)
<!--
Thank you for contributing to the project! 💜
Please see our [OSS process
document](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md#)
to get an idea of how we operate.
-->

## Which problem is this PR solving?

<please describe the issue>

- Closes https://github.com/honeycombio/helm-charts/issues/286

## Short description of the changes

- Updates the json schema file to enforce operator field to be required
and have a length of at least 1
- Update the values.yaml and README with a warning to stringify certain
operators

## How to verify that this has the expected result
Tested locally with `helm template`. If you provide `>`, or `!=` as an
operator you now get

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
refinery:
- rules.Samplers.testing.RulesBasedSampler.Rules.0.Conditions.0.Operator: String length must be greater than or equal to 1
```

Providing `>=` already caused an error.

---------

Co-authored-by: Kent Quirk <kentquirk@gmail.com>